export default {
    expressCom: {
        "yuantong": "圆通速递",
        "zhongtong": "中通快递",
        "yunda": "韵达快递",
        "shunfeng": "顺丰速运",
        "shentong": "申通快递",
        "youzhengguonei": "邮政快递包裹",
        "jtexpress": "极兔速递",
        "jd": "京东物流",
        "ems": "EMS",
        "debangkuaidi": "德邦快递",
        "youzhengdsbk": "邮政电商标快",
        "danniao": "菜鸟速递",
        "youzhengbk": "邮政标准快递",
        "zhongtongkuaiyun": "中通快运",
        "usps": "USPS",
        "jinguangsudikuaijian": "京广速递",
        "jingdongkuaiyun": "京东快运",
        "debangwuliu": "德邦物流",
        "kuayue": "跨越速运",
        "shunfengkuaiyun": "顺丰快运",
        "annengwuliu": "安能快运",
        "annto": "安得物流",
        "sxjdfreight": "顺心捷达",
        "yundakuaiyun": "韵达快运",
        "baishiwuliu": "百世快运",
        "fedex": "FedEx-国际件",
        "zhongtongguoji": "中通国际",
        "yimidida": "壹米滴答",
        "zhimakaimen": "芝麻开门",
        "ztky": "中铁快运",
        "ups": "UPS",
        "savor": "海信物流",
        "subida": "速必达",
        "dhl": "DHL-中国件",
        "rrs": "日日顺物流",
        "upsen": "UPS-全球件",
        "youshuwuliu": "优速",
        "jiayunmeiwuliu": "加运美",
        "japanposten": "日本(Japan Post)",
        "dhlen": "DHL-全球件",
        "tnjex": "明通国际快递",
        "youzhengguoji": "国际包裹",
        "zhaijibian": "宅急便",
        "chinapost": "中国邮政(CHINA POST)",
        "huitongkuaidi": "百世快递",
        "fedexus": "FedEx-美国件",
        "fedexcn": "Fedex-国际件-中文",
        "pingandatengfei": "平安达腾飞",
        "ewe": "EWE全球快递",
        "cainiaodajian": "菜鸟大件",
        "ronghui": "融辉物流",
        "baishiguoji": "百世国际",
        "emswuliu": "EMS物流",
        "xinfengwuliu": "信丰物流",
        "suteng": "速腾快递",
        "flextock": "Flextock",
        "timelytitan": "Titan泰坦国际速递",
        "stosolution": "申通国际",
        "xjdaishu": "袋鼠速递",
        "lianhaowuliu": "联昊通",
        "postnl": "荷兰邮政(PostNL international registered mail)",
        "suning": "苏宁物流",
        "zhuanyunsifang": "转运四方",
        "zhaijisong": "宅急送",
        "sgxpress": "SGXpress",
        "qhxyyg": "雪域易购",
        "ane66": "安能快递",
        "sagawa": "佐川急便",
        "huisenky": "汇森速运",
        "jindawuliu": "金大物流",
        "shunchangguoji": "顺昌国际",
        "taijin": "泰进物流",
        "btexpress": "邦泰快运",
        "dpdgermany": "DPD Germany",
        "cosco": "中远e环球",
        "sfwl": "盛丰物流",
        "xyjexpress": "西邮寄速递",
        "shunfenglengyun": "顺丰冷链",
        "disifang": "递四方",
        "yuxinwuliu": "宇鑫物流",
        "gotoubi": "UBI Australia",
        "sut56": "速通物流",
        "shenghuiwuliu": "盛辉物流",
        "ecmscn": "易客满",
        "hd": "宏递快运",
        "ztocc": "中通冷链",
        "baitengwuliu": "百腾物流",
        "jgwl": "景光物流",
        "longjun": "龙俊物流",
        "yuanzhijiecheng": "元智捷诚",
        "shpost": "同城快寄",
        "doortodoor": "CJ物流",
        "quantong56": "全通速递",
        "guexp": "全联速运",
        "hnydl56": "豫德隆物流",
        "auspost": "澳大利亚(Australia Post)",
        "anjie88": "安捷物流",
        "tnt": "TNT",
        "aae": "AAE-中国件",
        "jxad56": "成都捷信安达物流",
        "xiangyuwl56": "翔宇物流",
        "jieanda": "捷安达",
        "emsbg": "EMS包裹",
        "jiajiwuliu": "佳吉快运",
        "jumstc": "聚盟共建",
        "sdyonghui56": "君霖永辉物流",
        "yuananda": "源安达",
        "hnht56": "鸿泰物流",
        "sypost": "顺友物流",
        "goex": "时安达速递",
        "huahanwuliu": "华翰物流",
        "rokin": "荣庆物流",
        "viechina": "佰纳博通",
        "cht361": "诚和通",
        "nsf": "新顺丰(NSF)",
        "yangbaoguo": "洋包裹",
        "datianwuliu": "大田物流",
        "wlkgo": "窝里快购",
        "sja56": "四季安物流",
        "jtexpressmy": "J&T Express 马来西亚",
        "dpd": "DPD",
        "honghua": "鸿华物流",
        "jiayiwuliu": "佳怡物流",
        "shipgce": "飞洋快递",
        "auexpress": "澳邮中国快运",
        "newsway": "家家通快递",
        "xgdd56": "星光大道",
        "chaoyun": "超运快递",
        "cccc58": "中集冷云",
        "excocotree": "可可树美中速运",
        "aramex": "Aramex",
        "arkexpress": "方舟速递",
        "cjkoreaexpress": "大韩通运",
        "jkdsaas": "吉客道",
        "suyoda": "速邮达",
        "tzky": "铁中快运",
        "czlbwl": "凌邦物流",
        "yuantongguoji": "圆通国际",
        "aliexpress": "无忧物流",
        "banma": "斑马物流",
        "emsinten": "EMS-国际件-英文",
        "ftd": "富腾达国际货运",
        "sanzhi56": "三志物流",
        "szshihuatong56": "世华通物流",
        "wtgyl": "小泰智运",
        "gdkjk56": "快捷快物流",
        "jg56": "鲸广直运",
        "jialidatong": "嘉里大通",
        "lanjunsuyun": "岚骏速运",
        "emsguoji": "EMS-国际件",
        "sunjex": "新杰物流",
        "tiantian": "天天快递",
        "dekuncn": "德坤物流",
        "h30post": "30POST",
        "inpostysd": "邮速达",
        "ctoexp": "泰国中通CTO",
        "erqianjia56": "贰仟家物流",
        "exfresh": "安鲜达",
        "gaotian56": "高田物流",
        "a2u": "A2U速递",
        "benniaosuyun": "笨鸟速运",
        "disifangus": "递四方美国",
        "itaoexpress": "爱淘速递",
        "parcelforcecn": "英国邮政大包EMS",
        "stkd": "顺通快递",
        "ocs": "OCS",
        "passerbyaexpress": "顺捷美中速递",
        "rycc": "瑞云冷链",
        "sendtochina": "速递中国",
        "signedexpress": "签收快递",
        "yuntrack": "YunExpress",
        "cainiaoglobal": "菜鸟国际",
        "dushisc": "渡石冷链",
        "shunfenghk": "顺丰-繁体",
        "cdjx56": "岑邦物流",
        "feibaokuaidi": "飞豹快递",
        "gdjida56": "继达物流",
        "synship": "SYNSHIP快递",
        "unitedex": "联合速运",
        "xiaomiwuliu": "小米物流",
        "yuanfeihangwuliu": "原飞航",
        "zhongji": "中汲物流",
        "anxl": "安迅物流",
        "canpost": "加拿大(Canada Post)",
        "feikangda": "飞康达",
        "inpostuk": "InPost (UK)",
        "japanpost": "日本郵便",
        "ndwl": "南方传媒物流",
        "polarexpress": "极地快递",
        "tiandihuayu": "天地华宇",
        "dsukuaidi": "D速快递",
        "huolalawuliu": "货拉拉物流",
        "jsdexpress": "吉时达物流",
        "kingfreight": "货运皇",
        "nzzto": "新西兰中通",
        "sundarexpress": "顺达快递",
        "tnten": "TNT-全球件",
        "yw56": "燕文物流",
        "yzswuliu": "亚洲顺物流",
        "bht": "BHT",
        "changwooair": "昌宇国际",
        "concare": "中健云康",
        "ealceair": "东方航空物流",
        "hengbang": "恒邦物流",
        "jscpl": "江苏中邮",
        "longcps": "加拿大龙行速运",
        "manwah": "敏華物流",
        "ninjavan": "Ninja Van",
        "superb": "Superb Express",
        "wanjiawuliu": "万家物流",
        "xlobo": "Xlobo贝海国际",
        "yaoqi": "耀奇物流",
        "100mexpress": "百米快运",
        "1ziton": "一智通",
        "baifudongfang": "百福东方",
        "boyol": "贝业物流",
        "coe": "COE",
        "evri": "Evri(Hermes UK)",
        "fastgoexpress": "速派快递",
        "gls": "GLS",
        "guangdongyouzhengwuliu": "广东邮政",
        "highsince": "海欣斯快递",
        "jiachenexpress": "佳辰国际速递",
        "jtexpresssg": "J&T Express 新加坡",
        "kangrun": "康润物流",
        "koalaexp": "考拉速递",
        "lhexpressus": "联合速递",
        "lotteglogis": "lotteglogis",
        "nantianwuliu": "南天物流",
        "pengyuntong": "鹏运通物流",
        "pjbest": "品骏快递",
        "rufengda": "如风达",
        "szclyc": "车联天下",
        "szyudawl": "宇达物流",
        "tcxfx": "正鑫小飞侠",
        "tjkjwl": "泰实货运",
        "uspscn": "USPSCN",
        "wln": "万理诺物流",
        "yuandun": "远盾物流",
        "yuejiutong": "粤九通物流",
        "zhongyouwuliu": "中邮物流",
        "zlink": "三真驿道",
        "acilogistix": "ACI Logistix",
        "adlerlogi": "德国雄鹰速递",
        "anjiekuaidi": "青岛安捷快递",
        "anteraja": "Anteraja",
        "aotsd": "澳天速运",
        "auod": "澳德物流",
        "canpar": "Canpar",
        "changjiang": "长江国际速递",
        "chuangyi": "创一快递",
        "chuanxiwuliu": "传喜物流",
        "cnspeedster": "速舟物流",
        "cpsair": "华中快递",
        "dayangwuliu": "大洋物流",
        "dongjun": "成都东骏物流",
        "dpduk": "DPD UK",
        "euasia": "欧亚专线",
        "fastway": "Fastway Ireland",
        "ft56": "飞腾物流",
        "ftky365": "丰通快运",
        "ganzhongnengda": "能达速递",
        "haoxiangwuliu": "豪翔物流",
        "hengluwuliu": "恒路物流",
        "hexpress": "红树国际快递",
        "hkpost": "中国香港(HongKong Post)",
        "hltop": "海联快递",
        "hnfywl": "方圆物流",
        "huanqiuabc": "中国香港环球快运",
        "jcex": "jcex",
        "jinchengwuliu": "锦程物流",
        "juding": "聚鼎物流",
        "kuaijiesudi": "快捷速递",
        "lijisong": "成都立即送",
        "lubang56": "路邦物流",
        "luckyexpress": "吉运家物流",
        "luzun": "路尊物流",
        "meiquick": "美快国际物流",
        "nlebv": "亚欧专线",
        "oneexpress": "一速递",
        "postserv": "中华邮政",
        "qexpress": "易达通快递",
        "quanxintong": "全信通快递",
        "renyi": "仁艺物流",
        "royalmail": "英国小包(Royal Mail)",
        "sanhuwuliu": "叁虎物流",
        "scsujiada": "速佳达快运",
        "sczpds": "速呈",
        "shengchi": "圣驰物流",
        "shengtai": "晟泰物流",
        "stonewzealand": "申通新西兰",
        "stwles": "盛泰物流",
        "szuem": "联运通物流",
        "tcat": "黑猫宅急便",
        "tmwexpress": "明达国际速递",
        "ttkeurope": "天天欧洲物流",
        "tykd": "天翼快递",
        "ubonex": "优邦速运",
        "ubuy": "德国优拜物流",
        "uszcn": "转运中国",
        "weitepai": "微特派",
        "wfsywuliu": "五方速运",
        "wherexpess": "威盛快递",
        "wjkwl": "万家康物流",
        "xqd4000711238": "新骐点物流",
        "yamato": "黑猫雅玛多",
        "zhongsukuaidi": "中速快递",
        "ztcce": "中途速递",
        "139express": "139快递",
        "13ten": "13ten",
        "168express": "Antron Express",
        "17feia": "一起飞啊国际速运",
        "17post56": "一起投物流",
        "17postservice": "17 Post Service",
        "1dlexpress": "e递诺快递",
        "1express": "1express",
        "1hcang": "1号仓",
        "1shida": "壹世达",
        "2eziymy": "Yong Man Yi",
        "2go": "2GO",
        "360lion": "360 Lion Express",
        "4cus": "4cus",
        "51aoyue": "东莞澳越供应链",
        "666post": "易德国际",
        "7eleven": "7-ELEVEN",
        "816kf": "816kf",
        "8256ru": "BEL北俄国际",
        "8dt": "永利八达通",
        "99minutos": "99minutos",
        "aaacooper": "AAA Cooper Transportation",
        "abf": "ABF",
        "abs": "ABS courier & freight system",
        "abxexpress_my": "ABX Express",
        "acommerce": "aCommerce",
        "acscourier": "ACS Courier",
        "adaexpress": "明大快递",
        "adapost": "安达速递",
        "adicional": "Adicional Logistics",
        "adico": "Adico",
        "adiexpress": "安达易国际速递",
        "adp": "ADP国际快递",
        "adsone": "ADSone",
        "afghan": "阿富汗(Afghan Post)",
        "agility": "Agility Logistics",
        "agopost": "全程快递",
        "ahdf": "德方物流",
        "ahgbwl": "顺善发物流",
        "ahkbps": "卡邦配送",
        "air21": "AIR21",
        "airgtc": "加拿大民航快递",
        "airpak": "airpak expresss",
        "airtrans": "AIRTRANS",
        "airwingsindia": "Airwings Courier Express India",
        "aitworldwide": "AIT Worldwide Logistics",
        "ajex": "AJEX",
        "ajexpress": "捷记方舟",
        "ajlogistics": "澳捷物流",
        "al8856": "阿里电商物流",
        "aland": "奥兰群岛",
        "albania": "阿尔巴尼亚(Posta shqipatre)",
        "alfatrex": "AlfaTrex",
        "algeria": "Algeria",
        "allekurier": "AlleKurier",
        "alliedexpress": "ALLIED",
        "alljoylogistics": "Alljoy",
        "allstar56": "满天星国际物流",
        "alog": "心怡物流",
        "alphafast": "Alpha Fast",
        "amazon": "Amazon",
        "amazon_fba_swiship": "Swiship UK",
        "amazoncnorder": "亚马逊中国订单",
        "amazonin": "亚马逊印度",
        "amazonit": "Amazon Shipping (IT)",
        "amazonuk": "亚马逊英国",
        "ambroexpress": "Ambro Express",
        "amsegroup": "AMSEGROUP",
        "andorrapost": "安道尔邮政",
        "anicamboxexpress": "Anicam Box Express",
        "anjiatongcheng": "安家同城快运",
        "anjiexin56": "安捷信物流",
        "anjun_logistics": "Anjun Logistics",
        "anlexpress": "新干线快递",
        "anmin56": "安敏物流",
        "anposten": "爱尔兰(An Post)",
        "anserx": "斑头雁国际物流",
        "anshidi": "安时递",
        "anteparcel": "Ant Eparcel",
        "antillespost": "荷属安的列斯荷兰邮政(Antilles Post)",
        "anxindakuaixi": "安信达",
        "aolau": "AOL澳通速递",
        "aosu": "澳速物流",
        "apc": "APC Postal Logistics",
        "apgecommerce": "apgecommerce",
        "aplus100": "美国汉邦快递",
        "araskargo": "Aras Kargo",
        "arc": "ARC",
        "ariesfar": "艾瑞斯远",
        "arrowxl": "Arrow XL",
        "artlogexpress": "Art Logexpress",
        "aruba": "阿鲁巴[荷兰](Post Aruba)",
        "asendia": "阿森迪亚",
        "asendiade": "Asendia Germany",
        "asendiahk": "Asendia HK",
        "asendiauk": "Asendia UK",
        "asendiausa": "Asendia USA",
        "asetr": "ASE",
        "ashsh": "上海生生物流",
        "asiafly": "上海亚翔",
        "asmspain": "ASM",
        "astexpress": "安世通快递",
        "asyadexpress": "Asyad Express",
        "attskybox": "SKYBOX",
        "atuhoraexpress": "A TU HORA EXPRESS",
        "auadexpress": "澳达国际物流",
        "auex": "澳货通",
        "ausexpress": "澳世速递",
        "austa": "Austa国际速递",
        "austria": "奥地利(Austrian Post)",
        "autw": "澳台转运",
        "auvexpress": "AUV国际快递",
        "averittexpress": "Averitt",
        "axexpress": "澳新物流",
        "axlehire": "AxleHire",
        "ayh56": "云晖物流",
        "azerbaijan": "阿塞拜疆EMS(EMS AzerExpressPost)",
        "babru": "北北国际",
        "bahrain": "巴林(Bahrain Post)",
        "baipin": "佰品物流",
        "baishiyp": "百世云配",
        "bangladeshpost": "EMS 孟加拉国",
        "bangsongwuliu": "邦送物流",
        "baoxianda": "报通快递",
        "barbados": "巴巴多斯(Barbados Post)",
        "baxida": "巴西达",
        "bazirim": "皮牙子快递",
        "bbeex": "大黄蜂国际速递",
        "bcwelt": "BCWELT",
        "bdatong": "八达通",
        "bdcgcc": "BDC快递",
        "bdmnet": "BDM Corriere espresso",
        "beckygo": "佰麒快递",
        "bee001": "蜜蜂速递",
        "beebird": "锋鸟物流",
        "beeexpress": "BEE express",
        "beiou": "beiou express",
        "belgiumpost": "比利时(Belgium Post)",
        "belize": "伯利兹(Belize Postal)",
        "belizepost": "伯利兹邮政(Belize Post)",
        "belpost": "白俄罗斯(Belpochta)",
        "benin": "贝宁",
        "benniao": "笨鸟国际",
        "benteng": "奔腾物流",
        "bermudapost": "百慕大邮政(Bermuda Post)",
        "bester": "飛斯特",
        "bestfulfill": "Bestfulfill",
        "bestmy": "百世国际(马来西亚)",
        "bestvn": "BEST Express (Vietnam)",
        "betterlife": "東邮寄",
        "bettertrucks": "Better Trucks",
        "bflg": "上海缤纷物流",
        "bhposta": "bh-posta",
        "bhutan": "不丹邮政 Bhutan Post",
        "biaojikuaidi": "彪记快递",
        "birdsystem": "飞鸟国际物流",
        "bjemstckj": "北京EMS",
        "bjlgyt": "路港易通",
        "bjqywl": "青云物流",
        "bjshomedelivery": "bjshomedelivery",
        "bjxsrd": "鑫锐达",
        "bjytsywl": "远通盛源",
        "blex56": "奔力物流",
        "bljt56": "佰乐捷通",
        "bluecare": "Bluecare Express",
        "bluedart": "BlueDart",
        "bluestreak": "BlueStreak",
        "bmwlgj": "白马物流",
        "bmxps": "北美国际物流",
        "bnexp": "商盟",
        "bofeng": "博峰物流",
        "bohei": "波黑(JP BH Posta)",
        "bolivia": "玻利维亚",
        "bombinoexpress": "Bombino Express",
        "bondscouriers": "Bonds Couriers",
        "borderexpress": "Border-Express",
        "borderguru": "BorderGuru",
        "bosind": "堡昕德速递",
        "bosta": "Bosta",
        "botspost": "博茨瓦纳",
        "boxc": "BOXC",
        "boxinda": "博信达",
        "bphchina": "速方(Sufast)",
        "bpostinter": "比利时国际(Bpost international)",
        "bqcwl": "百千诚物流",
        "br1express": "BR1 Express",
        "brazilposten": "巴西(Brazil Post/Correios)",
        "bridgeexpress": "Bridge Express",
        "briems": "宏桥国际物流",
        "bring": "bring",
        "brt": "BRT",
        "brunei": "文莱(Brunei Postal)",
        "bsht": "百事亨通",
        "bsiscm": "佰事达",
        "btdair": "深圳宝通达",
        "btexp": "利佳顺",
        "buffaloex": "Buffalo",
        "buffaloexza": "BUFFALO ZA",
        "bulgarian": "保加利亚(Bulgarian Posts)",
        "burundipost": "布隆迪邮政(Burundi Post)",
        "buyer1688": "1688国际物流",
        "buylogic": "Buylogic",
        "buytong": "百通物流",
        "caboverdepost": "佛得角邮政(Correios Cabo Verde)",
        "cacc": "Cacc",
        "cacesapostal": "Cacesa南美专线",
        "caifengwl": "彩丰物流",
        "caledonia": "新喀里多尼亚[法国](New Caledonia)",
        "cambodia": "柬埔寨(Cambodia Post)",
        "camekong": "到了港",
        "campbellsexpress": "Campbell’s Express",
        "campost": "喀麦隆邮政(Cameroon Post)",
        "canadaposteway": "CPacket",
        "canhold": "能装能送",
        "canpostfr": "加拿大邮政",
        "cargolux": "卢森堡航空",
        "cargus": "Cargus",
        "carryflap": "Carry-Flap Co.,Ltd",
        "cbl": "CBL Logistica",
        "cbl_logistica": "CBL Logistics",
        "cbllogistics": "广州信邦",
        "cbo56": "钏博物流",
        "cbtsd": "北泰物流",
        "ccd": "次晨达物流",
        "cd3fwl": "中迅三方",
        "cdek": "CDEK",
        "cdl": "CDL",
        "cdxinchen56": "鑫宸物流",
        "celdt": "CEL 珲春畅达",
        "celeritas": "Celeritas",
        "ceskaposta": "捷克(Ceska Posta)",
        "cess": "国通快递",
        "ceva": "CEVA Logistics",
        "cevalogistics": "CEVA Logistic",
        "cex": "城铁速递",
        "cfss": "银雁专送",
        "cgsexpress": "超光速国际物流",
        "changyousudi": "畅邮速递",
        "chengda": "成达国际速递",
        "chengfeng": "顺阳供应链",
        "chengji": "城际快递",
        "chengning": "城宁供应链",
        "chengtong": "城通物流",
        "chengyangex": "程洋快递",
        "chile": "智利(Correos Chile)",
        "chinaicip": "卓志速运",
        "chinapostcb": "中邮电商",
        "chinaqingguan": "荣通国际",
        "chinarussia56": "俄必达A79",
        "chinasqk": "SQK国际速递",
        "chinastarlogistics": "华欣物流",
        "chinatzx": "同舟行物流",
        "chllog": "嘉荣物流",
        "chnexp": "中翼国际物流",
        "choicexp": "赛时国际货运",
        "chronopostfra": "法国大包、EMS-法文(Chronopost France)",
        "chronopostfren": "法国大包、EMS-英文(Chronopost France)",
        "chronopostport": "Chronopost Portugal",
        "chszhonghuanguoji": "CHS中环国际快递",
        "chukou1": "出口易",
        "chunfai": "中国香港骏辉物流",
        "chunilps": "Chunil Cargo",
        "cirroparcel": "CIRRO",
        "cititrans": "亦邦物流",
        "city56": "城市映急",
        "citylink": "City-Link",
        "citymail": "CityMail",
        "citysprint": "citysprint",
        "cjcentury": "CJ LOGISTICS",
        "cjdropshipping": "CJ Dropshipping",
        "cjpacket": "Cjpacket",
        "cjqy": "长吉物流",
        "ckeex": "城晓国际快递",
        "ckexpress": "CK物流",
        "clcz": "江苏诚通物流",
        "clevylinks": "CLEVY-LINKS",
        "cllexpress": "澳通华人物流",
        "cloudlogistics365": "群航国际物流",
        "cmkexpress": "晨明坤供应链",
        "cnair": "CNAIR",
        "cnausu": "中澳速递",
        "cncexp": "C&C国际速递",
        "cndexpress": "辰诺达国际物流",
        "cneulogistics": "中欧物流",
        "cnexps": "CNE",
        "cnilink": "CNILINK",
        "cnpex": "CNPEX中邮快递",
        "cnup": "CNUP 中联邮",
        "colicoli": "Colicoli",
        "colipu": "科力普物流",
        "colisprive": "Colis Privé",
        "colissimo": "法国小包(colissimo)",
        "collectplus": "Collect+",
        "collivery": "Collivery-net",
        "colombia": "哥伦比亚(4-72 La Red Postal de Colombia)",
        "colombiapost": "哥伦比亚邮政(Colombia Post)",
        "com1express": "商壹国际物流",
        "comethellas": "Comet Hellas",
        "comettech": "彗吉科技",
        "comexpress": "邦通国际",
        "conway": "Con-way Freight",
        "coolrunner": "Coolrunner",
        "coordinadora": "COODRDINADORA",
        "corporatecouriers": "Corporate couriers logistics",
        "correios": "莫桑比克(Correios de Moçambique)",
        "correo": "乌拉圭(Correo Uruguayo)",
        "correoargentino": "阿根廷(Correo Argentina)",
        "correos": "哥斯达黎加(Correos de Costa Rica)",
        "correosdees": "西班牙(Correos de Espana)",
        "correosexpress": "Correos Express",
        "cosex": "慧合物流",
        "cosmeticsnow": "Cosmetics Now",
        "courant": "Courant",
        "courierexe": "Courier Exe",
        "courierit": "Courier IT",
        "courierpost": "CourierPost",
        "couriersplease": "Couriers Please",
        "cpex": "凯普国际速运",
        "cqxingcheng": "重庆星程快递",
        "crazyexpress": "疯狂快递",
        "crhmd": "晨睿货满多",
        "csdexpress": "超时代供应链",
        "cseru": "CSE",
        "csuivi": "法国(La Poste)",
        "csxss": "新时速物流",
        "ctcexpress": "CTC-express",
        "cttexpress": "CTT Express",
        "cubapost": "古巴邮政(Cuba Post)",
        "cubyn": "Cubyn",
        "cuckooexpress": "布谷鸟速递",
        "cxchk": "CXC物流",
        "cyexpress": "创宇国际",
        "cypruspost": "塞浦路斯(Cyprus Post)",
        "cyxfx": "小飞侠速递",
        "czwlyn": "云南诚中物流",
        "dachser": "DACHSER",
        "dadaoex": "大道物流",
        "daipost": "DAI Post",
        "dajitongyun": "大集同运",
        "dande56": "丹递56",
        "dao365": "Dao365",
        "dasu": "达速物流",
        "dawnwing": "Dawn Wing",
        "dayonetrack": "Day One Track",
        "dayross": "Dayross",
        "dbschenker": "全球国际货运",
        "dcs": "DCS",
        "ddexpress": "DD Express",
        "dealersend": "DealerSend",
        "dealfy": "蒂尔物流",
        "dechuangwuliu": "深圳德创物流",
        "decnlh": "德中快递",
        "deksu": "德速电商物流",
        "delcart": "Delcart",
        "delhivery": "Delhivery",
        "deliverystations": "Delivery Station",
        "dellin": "Dellin",
        "delnext": "Delnext",
        "deltec": "Deltec Courier",
        "deployeg": "Deploy",
        "desworks": "澳行快递",
        "deutschepost": "德国(Deutsche Post)",
        "dfglobalex": "东风全球速递",
        "dflogis": "DFGL",
        "dfpost": "达方物流",
        "dfwl": "达发物流",
        "dgtransporte": "DG Transpote",
        "dhlactive": "DHL Active Tracing",
        "dhlbenelux": "DHL Benelux",
        "dhlde": "DHL-德国件(DHL Deutschland)",
        "dhlecommerce": "dhl小包",
        "dhles": "DHL 西班牙",
        "dhlfr": "DHL FR",
        "dhlglobalmail": "DHL电子商务",
        "dhlhk": "DHL HK",
        "dhlink": "Dhlink",
        "dhllogistics": "DHL全球货运",
        "dhlnetherlands": "DHL-荷兰(DHL Netherlands)",
        "dhlpoland": "DHL-波兰(DHL Poland)",
        "dhluk": "dhluk",
        "di5pll": "递五方云仓",
        "dianyi": "云南滇驿物流",
        "didasuyun": "递达速运",
        "dindon": "叮咚澳洲转运",
        "dingdong": "叮咚快递",
        "directlink": "Direct Link",
        "disifangau": "递四方澳洲",
        "djibouti": "吉布提",
        "dlvd": "DLVD",
        "dmlexpress": "大马鹿速运",
        "dmmnetwork": "DMM Network",
        "dongding": "东鼎物流",
        "donghanwl": "东瀚物流",
        "donghong": "东红物流",
        "doragate": "哆啦任意门",
        "dotzot": "Dotzot",
        "dpd_ireland": "DPD Ireland",
        "dpdat": "DPD Austria",
        "dpdbe": "DPD 比利时",
        "dpdch": "DPD Switzerland",
        "dpdcz": "DPD 捷克",
        "dpdfr": "法国DPD",
        "dpdgr": "DPD GR",
        "dpdhk": "DPD 香港",
        "dpdhr": "DPD Croatia",
        "dpdnl": "DPD Netherlands",
        "dpdpoland": "DPD Poland",
        "dpdpt": "葡萄牙DPD",
        "dpdro": "DPD Romania",
        "dpdru": "DPD RU",
        "dpdsk": "DPD SK",
        "dpe_express": "DPE Express",
        "dpex": "DPEX",
        "dpexen": "Toll",
        "dpeza": "DPE South Africa",
        "dpxexpress": "地平线速运",
        "dragonfe": "DF物流",
        "dreevo": "dreevo",
        "drivehailify": "Hailify",
        "driverfastgo": "老司机国际快递",
        "dropshipman": "Dropshipman",
        "dsv": "DSV",
        "dt8ang": "德淘邦",
        "dtd": "DTD",
        "dtdcindia": "DTDC India",
        "duxiuexp": "独秀国际",
        "dwz56": "递五洲国际物流",
        "dxdelivery": "DX Delivery",
        "dybservice": "DYB",
        "dyexpress": "大亿快递",
        "dyjexp": "深圳达运佳国际物流",
        "dylt": "Daylight Transport",
        "earlybird": "早鸟",
        "easyexpress": "EASY EXPRESS",
        "easymail": "Easy Mail",
        "ebowxp": "EBOEXP",
        "ecallturn": "E跨通",
        "ecan": "台湾宅配通快递",
        "ecargo": "Ecargo",
        "ecelogistics": "ECE Logistics",
        "ecfirstclass": "EC-Firstclass",
        "echo": "Echo",
        "ecmsglobal": "ECMS Express",
        "ecomexpress": "Ecom Express",
        "ecommercekz": "e-Commerce KZ",
        "ecoscooting": "ECOSCOOTING",
        "ecotransite": "东西E全运",
        "ecpostchina": "ECPOST",
        "ecuador": "厄瓜多尔(Correos del Ecuador)",
        "edaeuexpress": "易达快运",
        "edragon": "龙象国际物流",
        "efs": "EFS Post(平安快递)",
        "efspost": "EFSPOST",
        "efwtrack": "EFW Track",
        "egyexpress": "EGY Express Logistics",
        "egypt": "埃及(Egypt Post)",
        "egyptexpress": "Egypt Express",
        "ekart": "Ekart",
        "elianpostindex": "易连供应链",
        "eliant": "广州易连供应链",
        "elitebio": "昊通国际物流",
        "elogluxembourg": "Elog Luxembourg",
        "elsalvadorpost": "萨尔瓦多邮政(El Salvador Post)",
        "elta": "希腊包裹(ELTA Hellenic Post)",
        "eltahell": "希腊EMS(ELTA Courier)",
        "emileps": "Emile",
        "emirates": "阿联酋(Emirates Post)",
        "emiratesen": "阿联酋(Emirates Post)",
        "emms": "澳州顺风快递",
        "emonitoring": "波兰小包(Poczta Polska)",
        "emonitoringen": "波兰小包(Poczta Polska)",
        "empsexpress": "EMPS Express",
        "emsen": "EMS-英文",
        "emsluqu": "高考通知书",
        "emssouthafrica": "南非EMS",
        "emsukraine": "乌克兰EMS(EMS Ukraine)",
        "emsukrainecn": "乌克兰EMS-中文(EMS Ukraine)",
        "england": "英国(大包,EMS)",
        "envialia": "Envialia",
        "epanex": "泛捷国际速递",
        "eparcelhr": "eParcel Korea",
        "eparcelus": "Eparcel",
        "epgshipping": "ePost Global",
        "epost": "HFD E-post",
        "epspost": "联众国际",
        "equick_cn": "Equick China",
        "eretaillogistics": "eRetail logistics",
        "eripostal": "厄立特里亚",
        "eshippinggateway": "一海通",
        "eshunda": "俄顺达",
        "esnadexpress": "ESNAD Express",
        "esoway": "加拿大易速递",
        "espeedpost": "易速国际物流",
        "espost": "Espost",
        "est365": "东方汇",
        "estafeta": "Estafeta",
        "estafetausa": "Estafeta USA",
        "estes": "Estes",
        "eteenlog": "ETEEN专线",
        "ethiopia": "埃塞俄比亚(Ethiopian postal)",
        "ethiopian": "埃塞俄比亚(Ethiopian Post)",
        "etong": "E通速递",
        "etotal": "eTotal快递",
        "etowertech": "eTower",
        "etrak": "Etrak",
        "etscp": "亿泰",
        "etsexpress": "俄通收",
        "eucnrail": "中欧国际物流",
        "eucpost": "德国 EUC POST",
        "euexpress": "EU-EXPRESS",
        "euguoji": "易邮国际",
        "eupackage": "易优包裹",
        "eurodis": "Eurodis快递",
        "europe8": "败欧洲",
        "europeanecom": "europeanecom",
        "eusacn": "优莎速运",
        "everwellmarine": "长顺海运",
        "exapaq": "Exapaq",
        "exbtr": "飛斯特運通",
        "exelot": "Exelot",
        "expeditors": "Expeditors",
        "explorer56": "探路速运",
        "express2global": "E2G速递",
        "expresscourier": "Express Courier",
        "expressdy": "道壹供应链",
        "expresslj": "灵境供应链",
        "expressone": "Express One",
        "expressplus": "澳洲新干线快递",
        "exsuda": "E速达",
        "eyoupost": "易友通",
        "ezhuanyuan": "易转运",
        "fafalux": "邦太供应链",
        "famiport": "全家快递",
        "fandaguoji": "颿达国际快递-英文",
        "fangdi56": "方递物流",
        "fanqiu": "泛球物流",
        "fanyukuaidi": "凡宇快递",
        "fardarww": "颿达国际快递",
        "fargoodexpress": "发个货",
        "farlogistis": "泛远国际物流",
        "faroeislandspost": "法罗群岛邮政(Faroe Islands Post)",
        "fasthorseau": "Fast Horse Express (AU)",
        "fasthouseus": "Fast Horse (US)",
        "fastontime": "加拿大联通快运",
        "fastrakservices": "Fastrak Services",
        "fastway_nz": "Fastway New Zealand",
        "fastway_za": "Fastway South Africa",
        "fastzt": "正途供应链",
        "fbkd": "飞邦快递",
        "fdmlogistics": "FDM Logistics",
        "fds": "FDS",
        "fedexpl": "FedEx 波兰",
        "fedexuk": "FedEx-英国件(FedEx UK)",
        "fedexukcn": "FedEx-英国件",
        "fedroad": "FedRoad 联邦转运",
        "feihukuaidi": "飞狐快递",
        "feikuaida": "飞快达",
        "fenghuangkuaidi": "凤凰快递",
        "fengyee": "丰羿",
        "fercam": "FERCAM Logistics & Transport",
        "ferryboatlogistics": "摆渡一下",
        "fetchr": "Fetchr",
        "fietskoeriers": "fietskoeriers",
        "fiji": "斐济(Fiji Post)",
        "finland": "芬兰(Itella Posti Oy)",
        "firstflight": "First Flight",
        "firstline56": "壹号专线",
        "firstlogistics": "First Logistics",
        "firstmile": "FirstMile",
        "fishpost": "邮鱼科技",
        "flashexpress": "Flash Express",
        "flashexpressen": "Flash Express-英文",
        "flashexpressph": "FlashExpress 菲律宾",
        "fleetopticsinc": "舰队光学",
        "flexport": "Flexport",
        "flowerkd": "花瓣转运",
        "flysman": "飞力士物流",
        "flytexpress": "飞特物流",
        "flyway": "程光快递",
        "fodel": "FODEL",
        "fourpxus": "四方格",
        "fox": "FOX国际快递",
        "fragt": "fragt",
        "frayun": "法运",
        "frd": "富润德供应链",
        "freakyquick": "FQ狂派速递",
        "freightquote": "FREIGHTQUOTE",
        "fswuliu716": "帆盛物流",
        "ftlexpress": "法翔速运",
        "fujexp": "孚界国际",
        "fujisuyun": "富吉速运",
        "fulfillmen": "Fulfillmen",
        "fuliyuan": "富利源物流",
        "fzrexp": "Fzrexp",
        "gaopost": "高翔物流",
        "gaotieex": "高铁快运",
        "gaticn": "Gati-中文",
        "gatien": "Gati-英文",
        "gatikwe": "Gati-KWE",
        "gdct56": "广东诚通物流",
        "gdex": "GDEX",
        "gdqwwl": "全网物流",
        "gdrz58": "容智快运",
        "gdwse": "威速易供应链",
        "gdxp": "新鹏快递",
        "gdyhwl": "广东盈寰物流",
        "ge2d": "GE2D跨境物流",
        "geisgroup": "Geis Global Logistics",
        "geispl": "Geis Poland",
        "gelexpress": "GEL 快递",
        "geodis": "Geodis",
        "georgianpost": "格鲁吉亚(Georgian Pos)",
        "geswl": "上海翼速国际物流",
        "gexpress": "G EXpress",
        "gfdwuliu": "冠达丰物流",
        "ghanapost": "加纳",
        "ghl": "环创物流",
        "ghtexpress": "GHT物流",
        "giaohangnhanh": "Giao Hàng Nhanh",
        "gibraltar": "直布罗陀[英国]( Royal Gibraltar Post)",
        "giztix": "GIZTIX",
        "gjwl": "冠捷物流",
        "global99": "全球速运",
        "globalleader": "全球立达",
        "globalrouters": "印态跨境",
        "globaltracktrace": "globaltracktrace",
        "globegisticsinc": "Globegistics Inc",
        "glscanada": "GLS Canada",
        "glscz": "GLS 捷克共和国(GLS CZ)",
        "glshr": "GLS(HR)",
        "glsitaly": "GLSItaly",
        "glspakete": "GLS Germany",
        "glspl": "GLS Poland(GLS PL)",
        "glssk": "GLS Slovakia",
        "glsspain": "GLS Spain(GLS ES)",
        "glsus": "gls-us",
        "gml": "英脉物流",
        "gofly": "Gofly",
        "gofoexpress": "GOFO",
        "goglobalpost": "GlobalPost",
        "gogox": "GOGOX",
        "gojavas": "gojavas",
        "goldjet": "高捷快运",
        "gongsuda": "共速达",
        "gooday365": "日日顺智慧物联",
        "goodexpress": "固德供应链",
        "goodkuaidi": "GOOD快递",
        "goswift": "Go Swift",
        "gotofreight": "运连网",
        "grab": "Grab",
        "grandslamexpress": "Grand Slam Express",
        "greenland": "格陵兰[丹麦](TELE Greenland A/S)",
        "greenlandpost": "格陵兰岛邮政(Greenland Post)",
        "grivertek": "潍鸿",
        "grupoampm": "Grupo ampm",
        "gscq365": "哥士传奇速递",
        "gslexpress": "德尚国际速递",
        "gsm": "GSM",
        "gsous": "GSO(GLS US)",
        "gti56": "跨境易通",
        "gts": "GTS快递",
        "gttexpress": "GTT EXPRESS快递",
        "guangdongtonglu": "广东通路",
        "guangdongyongbang": "永邦快递",
        "guangyy56": "广运源国际物流",
        "guanting": "冠庭国际物流",
        "guatemalapost": "危地马拉邮政(Guatemala Post)",
        "guernsey": "根西岛",
        "guoeryue": "天天快物流",
        "guoshunda": "国顺达物流",
        "guosong": "国送快运",
        "guyana": "圭亚那",
        "gvpexpress": "宏观国际快递",
        "gwworld": "Gebrüder Weiss Germany",
        "gxwl": "光线速递",
        "gyjjwl": "贵阳佳吉",
        "gzanjcwl": "广州安能聚创物流",
        "gzbtygj": "宏海供应链",
        "gzxdgyl": "享道供应链",
        "gzxingcheng": "贵州星程快递",
        "h66": "货六六",
        "haidaibao": "海带宝",
        "haihongmmb": "海红for买卖宝",
        "haihongwangsong": "海红网送",
        "haimengsudi": "海盟速递",
        "haiwaihuanqiu": "海外环球",
        "haixingqiao": "海星桥快递",
        "haizhongzhuanyun": "海中转运",
        "handboy": "汉邦国际速递",
        "hanfengjl": "翰丰快递",
        "hangjia": "航家快运",
        "hangrui": "上海航瑞货运",
        "hangyu": "航宇快递",
        "hanjin": "Hanjin",
        "hanxin": "汉信快递",
        "hanxuan": "瀚轩国际物流",
        "haokangwl": "豪康物流",
        "haypost": "亚美尼亚(Haypost-Armenian Postal)",
        "hctexpress": "新竹物流HCT",
        "hdcexpress": "汇达物流",
        "heibaowuliu": "黑豹物流",
        "heimao56": "黑猫速运",
        "hellmann": "Hellmann",
        "helthjem": "挪威HELTHJEM",
        "hengrui56": "恒瑞物流",
        "hepsijet": "HepsiJET",
        "hermes": "Hermes",
        "hermes_de": "Hermes Germany",
        "hermesborderguru": "Hermes Borderguru",
        "hermesworld": "Hermesworld",
        "heute": "货易达",
        "hexinexpress": "合心速递",
        "hgy56": "环国运物流",
        "hgzx": "韩润物流",
        "hhair56": "华瀚快递",
        "hhjy56": "华航吉运",
        "hhyexpress": "恒好运物流",
        "highway": "Highway",
        "hilife": "莱尔富",
        "hivewms": "海沧无忧",
        "hjs": "猴急送",
        "hjwl": "汇捷物流",
        "hjyt56": "恒捷宇通",
        "hkdexpress": "HKD",
        "hkeex": "飞豹速递",
        "hkems": "云邮跨境快递",
        "hkglobalsea": "環海快運",
        "hkhuaguang": "华光国际快运",
        "hkkerryexpress": "TGX精英速运",
        "hkposten": "中国香港(HongKong Post)英文",
        "hlpgyl": "共联配",
        "hlyex": "好来运",
        "hmus": "华美快递",
        "hnfy": "飞鹰物流",
        "hnqst": "河南全速通",
        "hnssd56": "顺时达物流",
        "hnyqf": "益企发物流",
        "hnzqwl": "中强物流",
        "holisollogistics": "Holisol",
        "homecourier": "如家国际快递",
        "honamlogis": "韩国友利",
        "honduras": "洪都拉斯",
        "hongbeixin": "红背心",
        "hongjie": "宏捷国际物流",
        "hongpinwuliu": "宏品物流",
        "hongyunfa56": "宏运发物流",
        "hongywl": "红远物流",
        "honold": "Honold Germany",
        "hotwms": "皇家云仓",
        "houndexpress": "Hound Express",
        "hoyangexpress": "弘扬物流",
        "hpexpress": "海派国际速递",
        "hplogistics": "弘鹏物流",
        "hqtd": "环球通达",
        "hrbguoo": "国欧物流",
        "hrbsydrd": "速远同城快递",
        "hrbzykd": "卓烨快递",
        "hre": "高铁速递",
        "hrex": "锦程快递",
        "hrparcel": "hrparcel",
        "hrvatska": "克罗地亚(Hrvatska Posta)",
        "hsdex": "鸿盛达",
        "hsdexpress": "寰世达国际物流",
        "hsgtsd": "海硕高铁速递",
        "ht22": "海淘物流",
        "htexpress": "慧通",
        "htkjwl": "环通跨境物流",
        "htongexpress": "华通快运",
        "httx56": "汇通天下物流",
        "huada": "华达快运",
        "huandonglg": "环东物流",
        "huangmajia": "黄马甲",
        "huanqiu": "环球速运",
        "huaqikuaiyun": "华企快运",
        "huaxiahuoyun": "华夏货运",
        "huaxiexpress": "华熙国际",
        "huayuex": "华宇物流",
        "hubologistics": "巨宝物流",
        "huidaexpress": "美国汇达快递",
        "huif56": "汇峰物流",
        "huilin56": "汇霖大货网",
        "huilogistics": "荟千物流",
        "huiqiangkuaidi": "汇强快递",
        "humpline": "驼峰国际",
        "hungary": "匈牙利(Magyar Posta)",
        "hunterexpress": "hunter Express",
        "huoban": "兰州伙伴物流",
        "hutongwuliu": "户通物流",
        "hxlinc": "华兴物流",
        "hyeship": "鸿远物流",
        "hyk": "上海昊宏国际货物",
        "hywuliu": "中电华远物流",
        "hyytes": "恒宇运通",
        "hzchgj": "川和国际",
        "hzdr": "天鸽快运",
        "hzpl": "华航快递",
        "hzys56": "禹盛快递",
        "ibcourier": "IB Courier",
        "ibuy8": "爱拜物流",
        "iceland": "冰岛(Iceland Post)",
        "icscourier": "ICS courier",
        "idada": "大达物流",
        "idexpress": "ID Express",
        "idslogistik": "IDS Germany",
        "iepost": "IEPost",
        "iex": "泛太优达",
        "igcaexpress": "无限速递",
        "ikyi": "精翼运通",
        "ilinexpress": "Ural乌拉尔国际物流",
        "ilogen": "logen路坚",
        "ilyang": "ILYANG",
        "imexglobal": "IMEX Global Solutions",
        "imile": "iMile",
        "imlb2c": "艾姆勒",
        "india": "印度(India Post)",
        "indonesia": "印度尼西亚EMS(Pos Indonesia-EMS)",
        "indonesiapost": "印度尼西亚邮政(Indonesia Post)",
        "indopaket": "INDOPAKET",
        "inposdom": "多米尼加(INPOSDOM – Instituto Postal Dominicano)",
        "inpost_paczkomaty": "InPost Paczkomaty",
        "intelcom": "Intelcom Express",
        "interjz": "捷运达快递",
        "interlink": "Interlink Express",
        "internetexpress": "Intexpress",
        "interparcel": "Interparcel",
        "iparcel": "UPS i-parcel",
        "iquickfish": "快飞鱼",
        "iran": "伊朗(Iran Post)",
        "israelpost": "以色列(Israel Post)",
        "isunnyway": "星锐国际物流",
        "italiane": "意大利(Poste Italiane)",
        "italysad": "Italy SDA",
        "ixpress": "IXPRESS",
        "iyoungspeed": "驿扬国际速运",
        "jamaicapost": "牙买加(Jamaica Post)",
        "jancoecommerce": "Janco",
        "jancoexpress": "骏高速运",
        "janio": "janio",
        "jayeek": "Jayeek",
        "jayonexpress": "Jayon Express (JEX)",
        "jcexpress": "深圳晶晟国际物流",
        "jchexp": "JCH",
        "jcsuda": "嘉诚速达",
        "jcwexpress": "JCW",
        "jdexpressusa": "骏达快递",
        "jdiex": "JDIEX",
        "jdkuaiyun": "京递快运",
        "jdpplus": "急递",
        "jerseypost": "泽西岛",
        "jet": "极兔国际",
        "jetexpresseg": "Jet Express",
        "jetexpressgroup": "澳速通国际速递",
        "jetexpresszh": "J&T Express",
        "jetship": "Jet-Ship Worldwide",
        "jetstarexp": "捷仕",
        "jetzh": "极兔国际中文",
        "jhx56": "佳豪鑫物流",
        "jiacheng": "佳成快递",
        "jiajiatong56": "佳家通货运",
        "jiajiawl": "加佳物流",
        "jiajikuaidi": "佳吉快递",
        "jiajisong": "加急送",
        "jiaxianwuliu": "嘉贤物流",
        "jiayouexp": "佳邮国际",
        "jiazhoumao": "加州猫速递",
        "jieborne": "捷邦物流",
        "jieshitong": "捷世通物流",
        "jiguang": "极光转运",
        "jinan": "金岸物流",
        "jinduan": "近端",
        "jingleexpressx": "Jingle Express",
        "jingshun": "景顺物流",
        "jinyuekuaidi": "晋越快递",
        "jisu": "盈通物流",
        "jisukd": "极速速运",
        "jiujiuwl": "久久物流",
        "jiuyescm": "九曳供应链",
        "jiuyicn": "久易快递",
        "jixianda": "急先达",
        "jixiangyouau": "吉祥邮(澳洲)",
        "jjx888": "佳捷翔物流",
        "jmguoxun": "国迅物流",
        "jne": "JNE",
        "jnet": "J-NET捷网",
        "joeyco": "Joeyco",
        "joomlogistics": "Joomlogistics",
        "jordan": "约旦(Jordan Post)",
        "joyingbox": "飞盒跨境",
        "jpsgjwl": "捷谱斯国际物流",
        "jsdky": "极速达物流",
        "jsexp": "急速国际",
        "jssdt56": "时达通",
        "jtexpressae": "极兔快递阿联酋",
        "jtexpressbr": "J&T Express Brazil",
        "jtexpresseg": "极兔快递埃及站",
        "jtexpressmx": "极兔速递(墨西哥)",
        "jtexpressph": "J&T Express 菲律宾",
        "jtexpressth": "J&T Express 泰国",
        "jtexpressvn": "JT Express VN",
        "jtotc": "吉通同城",
        "jtx168": "吉天下快运",
        "jumia": "Jumia",
        "jumsz": "聚盟物流",
        "junfengguoji": "骏丰国际速递",
        "jusdasr": "准时达跨境",
        "juwu": "聚物物流",
        "juxiex": "驹隙物流",
        "juyuanwuliu": "聚缘物流",
        "juzhongda": "聚中大",
        "jxfex": "集先锋快递",
        "kahaexpress": "Kaha Epress",
        "kaigenlogistics": "海源国际",
        "kajie": "卡捷物流",
        "kangaroo": "Kangaroo Express",
        "kart2door": "Kart2door",
        "kawa": "嘉华",
        "kazpost": "哈萨克斯坦(Kazpost)",
        "kcs": "KCS",
        "kdexp": "韩国京东",
        "kejie": "科捷物流",
        "kenya": "肯尼亚(POSTA KENYA)",
        "kerryecommerce": "嘉里电子商务",
        "kerryexpressvn": "Kerry Express",
        "kerrytec": "Kerry Tec",
        "kerrythailand": "Kerry Express-泰国",
        "kerrythailanden": "Kerry Express-泰国",
        "kerrytj": "嘉里大荣物流",
        "kerrytransport": "嘉里环球",
        "keypon": "启邦国际物流",
        "kfwnet": "快服务",
        "kgmhub": "KGM Hub",
        "khzto": "柬埔寨中通",
        "kingruns": "Kingruns土耳其鲸仓",
        "kingtrans": "壹启物流",
        "kjy": "顺邦科技物流",
        "kn": "Kuehne + Nagel",
        "koali": "番薯国际货运",
        "komonexpress": "可蒙国际",
        "koreapost": "韩国(Korea Post)",
        "koreapostcn": "韩国邮政",
        "koreapostkr": "韩国邮政韩文",
        "kqtwl": "凯骐通物流",
        "krtao": "淘韩国际快递",
        "ksudi": "快速递",
        "kuaidawuliu": "快达物流",
        "kuaijiewuliu": "快捷物流",
        "kuaika": "快卡",
        "kuaiyan": "快雁",
        "kuajingyihao": "跨境壹号",
        "kuehne": "Kuehne",
        "kuehnenagel": "Kuehne+Nagel",
        "kunyiyc": "Kunyi",
        "kunyoung": "KUNYONG EXPRESS",
        "kurasi": "KURASI",
        "kuwaitpost": "科威特邮政(Kuwait Post)",
        "kwe": "KWE",
        "kwt56": "京华达物流",
        "kxda": "凯信达",
        "kylm360": "快运联盟",
        "kyrgyzpost": "吉尔吉斯斯坦(Kyrgyz Post)",
        "la911": "鼎润物流",
        "lahuoex": "拉火速运",
        "lanbiaokuaidi": "蓝镖快递",
        "landmarkglobal": "Landmark Global",
        "lanhukuaidi": "蓝弧快递",
        "lanqichuhai": "蓝鳍出海",
        "lao": "老挝(Lao Express)",
        "laposte": "塞内加尔",
        "lapostemonaco": "摩纳哥邮政(Monaco Post)",
        "lasership": "LaserShip",
        "lasy56": "林安物流",
        "latamyou": "LATAM YOU",
        "latvia": "拉脱维亚(Latvijas Pasts)",
        "latviaen": "拉脱维亚(Latvijas Pasts)",
        "lazada": "Lazada (LGS) 快递",
        "lb56": "蓝豹云仓供应链",
        "lbbk": "立白宝凯物流",
        "lbc56": "LBC Express",
        "lbex": "龙邦物流",
        "lbexps": "立邦国际物流",
        "lbt56": "莱比特物流",
        "lc56": "禄昌物流",
        "ldlog": "龙迅国际物流",
        "ldxpres": "林道国际快递-英文",
        "ldzy168": "两点之间",
        "leader609": "立德国际物流",
        "ledaexpress": "乐达全球速递",
        "ledaowuliu": "楽道物流",
        "ledii": "乐递供应链",
        "legionexp": "LEGION EXPRESS",
        "leopard": "云豹国际货运",
        "leopardschina": "LWE云豹",
        "leshines": "想乐送",
        "lesoon": "丽迅物流",
        "lesotho": "莱索托(Lesotho Post)",
        "letseml": "美联快递",
        "lexship": "Laxship",
        "lfexpress": "龙枫国际快递",
        "lianbangkuaidi": "联邦快递",
        "lianbangkuaidien": "联邦快递-英文",
        "liangdian": "亮点快运",
        "lianyu": "联宇物流",
        "lianyun": "联运快递",
        "libanpost": "黎巴嫩(Liban Post)",
        "liccarditrasporti": "LICCARDI",
        "liechtensteinpost": "列支敦士登邮政(Liechtenstein Post)",
        "liefergruen": "Liefergrün",
        "lietuvospost": "立陶宛邮政(Lithuania Post)",
        "lineclear": "Line Clear Express & Logistics",
        "lineone": "一号线",
        "linex": "Linex",
        "lingsong": "领送送",
        "lionparcel": "Lion Parcel",
        "lishi": "丽狮物流",
        "lite56": "Lite Express",
        "liujiashen": "润禾物流",
        "lixunwuliu": "利迅物流",
        "lizhan": "力展物流",
        "lmfex": "良藤国际速递",
        "lmparcel": "六脉速运",
        "lnet": "新易泰",
        "lntjs": "特急送",
        "loadbugs": "Loadbugs",
        "logisters": "随波物流",
        "logisticacanaria": "Asigna",
        "logistics": "華信物流WTO",
        "lonestar": "lonestar",
        "longbiao56": "龙飙物流",
        "longfx": "LUCFLOW EXPRESS",
        "longlangkuaidi": "隆浪快递",
        "longvast": "长风物流",
        "loomisexpress": "Loomis Express",
        "lpexpress": "LP Express",
        "lsexpress": "6LS EXPRESS",
        "lsgykd": "龙尚广源快递",
        "ltexp": "乐天速递",
        "ltparcel": "联通快递",
        "luben": "陆本速递 LUBEN EXPRESS",
        "luckyfastex": "吉捷国际速递",
        "lundao": "论道国际物流",
        "lutong": "鲁通快运",
        "luxembourg": "卢森堡(Luxembourg Post)",
        "luxembourgde": "卢森堡(Luxembourg Post)",
        "luxembourgfr": "卢森堡(Luxembourg Post)",
        "luyao": "路遥物流",
        "lwe": "LWE",
        "lx56": "龙兴物流",
        "lxwlgyl": "种心速运",
        "macao": "中国澳门(Macau Post)",
        "macedonia": "马其顿(Macedonian Post)",
        "madrooex": "上海翼瀚",
        "maersk": "Maersk",
        "mailamericas": "mailamericas",
        "mailongdy": "迈隆递运",
        "mainfreight": "Mainfreight",
        "malaysiaems": "马来西亚大包、EMS(Malaysia Post(parcel,EMS))",
        "malaysiapost": "马来西亚小包(Malaysia Post(Registered))",
        "maldivespost": "马尔代夫邮政(Maldives Post)",
        "malta": "马耳他(Malta Post)",
        "mangguo": "芒果速递",
        "mapleexpress": "今枫国际快运",
        "maratrack": "环世捷运物流",
        "mascourierservice": "MAS Courier Servic",
        "matdespatch": "Matdespatch快递",
        "matkahuolto": "Matkahuolto",
        "mauritius": "毛里求斯(Mauritius Post)",
        "maxcellents": "Maxcellents Pte Ltd",
        "maxeedexpress": "澳洲迈速快递",
        "mcexpress": "茂聪国际物流",
        "mchy": "木春货运",
        "mcih": "MCIH国际快递",
        "mecs": "Middle East Courier service",
        "med56": "金域达物流",
        "meest": "中乌融盛速递",
        "meestgroup": "Meest快递",
        "meibang": "美邦国际快递",
        "meidaexpress": "美达快递",
        "meiguokuaidi": "美国快递",
        "meitai": "美泰物流",
        "meixi": "美西快递",
        "mengyuan56": "孟元物流",
        "merage": "Merage",
        "mexico": "墨西哥(Correos de Mexico)",
        "mexicodenda": "Mexico Senda Express",
        "mhafly": "梦和爱贸易",
        "mhgjexpress": "茂泓国际",
        "mhsy": "名航速运",
        "miaowu": "喵物配送",
        "milkyway": "银河物流",
        "minghangkuaidi": "民航快递",
        "mingliangwuliu": "明亮物流",
        "miuson": "深圳淼信国际物流",
        "mkdexpress": "美卡多物流",
        "mlw": "美乐维冷链物流",
        "mmlogi": "猛犸速递",
        "mol": "Mitsui OSK Lines",
        "moldova": "摩尔多瓦(Posta Moldovei)",
        "mondialrelay": "Mondial Relay",
        "mongolpost": "蒙古国(Mongol Post)",
        "montenegro": "黑山(Posta Crne Gore)",
        "morelink56": "MoreLink",
        "morocco": "摩洛哥 ( Morocco Post )",
        "mosuda": "魔速达",
        "movin": "Movin",
        "mrw": "MRW",
        "mtlogistik": "MT速运",
        "mxe56": "中俄速通(淼信)",
        "mxpress2u": "M-xpress",
        "myaustrianpost": "澳邮欧洲专线平邮",
        "mydidadi": "DIDADI",
        "myhermes": "MyHermes",
        "myhes": "Hermes Einrichtungs Service",
        "myib": "MyIB",
        "myjamexpress": "Jam Express",
        "mykn": "myKN",
        "mylerz": "mylerz",
        "mypostonline": "Mypostonline",
        "mz56": "铭志国际",
        "mzlyuanhao": "元昊国际",
        "nacex": "Nacex",
        "nalexpress": "新亚物流",
        "namibia": "纳米比亚(NamPost)",
        "nandan": "NandanCourier",
        "nanjingwoyuan": "南京沃源",
        "naqel": "NAQEL Express",
        "nationex": "Nationex",
        "nationwide2u": "Nationwide Express",
        "nbhtt": "早道佳",
        "nbky": "南北快运",
        "nebuex": "星云速递",
        "nederlandpost": "荷兰速递(Nederland Post)",
        "nepalpost": "尼泊尔(Nepal Postal Services)",
        "networkcourier": "Network Courier",
        "newaytransport": "Neway",
        "newgistics": "Newgistics",
        "newzealand": "新西兰(New Zealand Post)",
        "nexive": "Nexive",
        "nezhasuyun": "哪吒速运",
        "nhans": "Nhans Solutions",
        "nicaraguapost": "尼加拉瓜邮政(Nicaragua Post)",
        "nigerianpost": "尼日利亚(Nigerian Postal)",
        "nightline": "Nightline",
        "ninjavanmy": "Ninja Van(马来西亚)",
        "ninjavanph": "Ninja Van(菲律宾)",
        "ninjavanth": "Ninja Van(泰国)",
        "ninjaxpress": "ninja xpress",
        "nipponexpress": "Nippon Express",
        "niuniuda": "牛牛达快运",
        "niuzaiexpress": "牛仔速运",
        "njfeibao": "金陵飞豹快递",
        "njhaobo": "浩博物流",
        "njhzlh": "南京合纵连横物流",
        "nle": "NLE",
        "nmhuahe": "华赫物流",
        "nokcourier": "Nok Courier",
        "norsk_global": "Norsk Global",
        "northline": "Northline",
        "novaposhta": "Nova Poshta",
        "noxnighttime": "NOX",
        "ntlogistics": "Ntlogistics-vn",
        "ntlsgj": "绿色国际",
        "nuokelai": "诺客来",
        "nuoyaao": "偌亚奥国际快递",
        "nuvoex": "NuvoEx",
        "nxtwuliu": "诺信特快递",
        "nyk": "NYK Line",
        "nzcouriers": "Nzcouriers",
        "ocaargen": "OCA Argentina",
        "ocpost": "OC-Post",
        "ocsindia": "﻿OCS ANA Group",
        "ocsworldwide": "OCS Worldwide",
        "ofo56": "南北通国际货代",
        "ogilogistic": "万国国际",
        "olddominion": "Old Dominion Freight Line",
        "oman": "阿曼(Oman Post)",
        "omgoexpress": "OmgoExpress",
        "omni2": "无限配",
        "omniparcel": "Omni Parcel",
        "omniva": "爱沙尼亚(Eesti Post)",
        "oneworldexpress": "One World Express",
        "ontrac": "OnTrac",
        "opek": "OPEK",
        "opex": "OPEX",
        "orangeconnex": "橙联股份",
        "orangeds": "OrangeDS",
        "orlenpaczka": "Orlen Paczka",
        "osmworldwide": "Osmworldwide",
        "oulalaexpress": "Oulala",
        "overnitenet": "Overnite印度快递",
        "overseaex": "波音速递",
        "overseasfrems": "EMS 海外领地法国",
        "overseaslogistics": "Overseas Logistics 印度快递",
        "packeta": "Packeta",
        "packfleet": "Packfleet",
        "packlink": "Packlink",
        "pakistan": "巴基斯坦(Pakistan Post)",
        "panama": "巴拿马",
        "panasiachina": "泛亚国际",
        "pandionpro": "Piggycars US",
        "pandulogistics": "Pandu Logistics",
        "paraguay": "巴拉圭(Correo Paraguayo)",
        "parcel100": "Parcel100",
        "parcel2go": "parcel2go",
        "parcelchina": "诚一物流",
        "parcelexpress": "Parcel Express",
        "parcelforce": "英国大包、EMS(Parcel Force)",
        "parcelled": "Parcelled.in",
        "parcelport": "Parcelport",
        "parknparcel": "Park N Pracel",
        "passportshipping": "Passport Shipping",
        "passtheparcel": "Pass The Parcel",
        "paxel": "paxel",
        "paxelen": "paxelen",
        "pcaexpress": "PCA Express",
        "pcfcorp": "PCF",
        "pcwl56": "普畅物流",
        "pdstow": "全球速递",
        "peex": "派尔快递",
        "peisihuoyunkuaidi": "配思货运",
        "peixingwuliu": "陪行物流",
        "pengyuanexpress": "鹏远国际速递",
        "peppaship": "佩奇集运",
        "perfectservice": "Perfect Service",
        "peru": "秘鲁(SERPOST)",
        "pesto": "Presto",
        "pfcexpress": "皇家物流",
        "pflogistics": "Parcel Freight Logistics",
        "phlpost": "菲律宾(Philippine Postal)",
        "pickrr": "Pickrr",
        "pickupp": "pickupp",
        "piggyship": "Piggycars",
        "pinsuxinda": "品速心达快递",
        "pinxinkuaidi": "品信快递",
        "pioneer": "先锋国际快递",
        "pitneybowes": "Pitney Bowes",
        "pittohio": "PITTOHIO",
        "pkdexpress": "派刻达",
        "pmt0704be": "龙行天下",
        "pochta": "俄罗斯邮政(Russian Post)",
        "polarisexpress": "北极星快运",
        "ponyexpress": "Pony Express",
        "portugalctt": "葡萄牙(Portugal CTT)",
        "portugalctten": "葡萄牙(Portugal CTT)",
        "portugalseur": "Portugal Seur",
        "posindonesia": "POS INDONESIA",
        "posta": "坦桑尼亚(Tanzania Posts Corporation)",
        "postabezhranic": "Posta Bze Hranic",
        "postaplus": "PostaPlus",
        "postdanmarken": "丹麦(Post Denmark)",
        "postenab": "PostNord(Posten AB)",
        "postennorge": "挪威(Posten Norge)",
        "postex": "PostEX",
        "posthaste": "posthaste",
        "postnlchina": "荷兰邮政-中国件",
        "postnlcn": "荷兰邮政-中文(PostNL international registered mail)",
        "postnlpacle": "荷兰包裹(PostNL International Parcels)",
        "postnord": "PostNord Logistics",
        "postone": "Post One",
        "postpng": "巴布亚新几内亚(PNG Post)",
        "ppsuyun": "PP速运",
        "pressiode": "Pressiode",
        "primamulticipta": "PT Prima Multi Cipta",
        "promeddel": "ProMed Deliversy",
        "ptpexpress": "PTP EXPRESS",
        "ptsexpress": "PTS Worldwide Express",
        "ptt": "土耳其",
        "purolator": "Purolator",
        "pyexpress": "派优供应链",
        "pzhjst": "急顺通",
        "qbexpress": "秦邦快运",
        "qdants": "ANTS EXPRESS",
        "qesd": "7E速递",
        "qhtchina": "深圳市全汇通物流",
        "qhxykd": "雪域快递",
        "qianli": "千里速递",
        "qichen": "启辰国际速递",
        "qinling": "秦岭智能速运",
        "qinyuan": "秦远物流",
        "qiyue": "琪悦物流",
        "qlinyun": "麒麟物流",
        "qlx56": "庆隆物流",
        "qpost": "卡塔尔(Qatar Post)",
        "qskdyxgs": "千顺快递",
        "quanchuan56": "全川摩运",
        "quanfengkuaidi": "全峰快递",
        "quanjitong": "全际通",
        "quanritongkuaidi": "全日通",
        "quansu": "全速物流",
        "quansutong": "全速通",
        "quantium": "Quantium",
        "quanyikuaidi": "全一快递",
        "quanyiwuliu": "景县全一物流",
        "quickwaysc": "瞬程物流",
        "quiken": "Quiken",
        "qulaitech": "去来冷链",
        "qwintry": "Qwintry",
        "qxpress": "Qxpress",
        "qyexp": "前雨国际",
        "qzx56": "全之鑫物流",
        "r2slogistics": "R2S Logistics",
        "raben": "Raben Group",
        "rafph": "RAF Philippines",
        "raiderex": "RaidereX",
        "ramgroup_za": "RAM",
        "rapidocargoeg": "Rapido Cargo Egypt",
        "rct56": "润成通",
        "redchains": "元红供应链",
        "redexpress": "Red Express",
        "redpack": "Redpack Mexico",
        "redur": "Redur",
        "redur_es": "Redur Spain",
        "relex": "RELEX",
        "renrenex": "人人转运",
        "rensu56": "仁速物流",
        "renyuanwuliu": "任远物流",
        "republic": "叙利亚(Syrian Post)",
        "rhenus": "RHENUS",
        "rhtexpress": "睿和泰速运",
        "riyuwuliu": "日昱物流",
        "rjexpress": "睿捷国际物流",
        "rjtcsd": "锐界同城速递",
        "rl_carriers": "RL Carriers",
        "rlgaus": "澳洲飞跃物流",
        "roadbull": "Roadbull Logistics",
        "romanian": "罗马尼亚(Posta Romanian)",
        "rongyu": "融跃速运",
        "royal": "royal mail internationa",
        "royalshipments": "Royal Shipments",
        "rpx": "rpx",
        "rpxid": "RPX Indonesia",
        "rpxonline": "RPX保时达国际快递",
        "rrdonnelley": "RR Donnelley",
        "rrskx": "日日顺快线",
        "rrthk": "日日通国际",
        "rrts": "ROADRUNNER FREIGHT",
        "ruidianyouzheng": "瑞典(Sweden Post)",
        "ruidianyouzhengen": "瑞典(Sweden Post)",
        "runbail": "润百特货",
        "runhengfeng": "全时速运",
        "ruston": "Ruston俄速通",
        "rwanda": "卢旺达(Rwanda i-posita)",
        "rzyexpress": "RZY Express",
        "safexpress": "Safexpress",
        "sagawaen": "佐川急便-英文",
        "saialtl": "Saia LTL Freight",
        "saiaodimmb": "赛澳递for买卖宝",
        "saicheng": "赛诚国际物流",
        "sailpost": "Sailpost",
        "salvador": "Correo El Salvador",
        "sameday": "Sameday",
        "samoa": "萨摩亚(Samoa Post)",
        "sanle56": "三乐物流",
        "sanmarinopost": "圣马力诺邮政(San Marino Post)",
        "sanshengco": "三盛快递",
        "sanstar": "盛德国际墨西哥物流",
        "santaisudi": "三态速递",
        "sapexpress": "SAP EXPRESS",
        "saudipost": "沙特阿拉伯(Saudi Post)",
        "scaexpress": "Sca Express",
        "sccod": "丰程物流",
        "sccs": "SCCS",
        "scgexpress": "SCG Express",
        "scglogistics": "SCG",
        "scic": "中加国际快递",
        "scxingcheng": "四川星程快递",
        "sd138": "泰国138国际物流",
        "sdhscm": "闪电猴物流",
        "sdkexpress": "斯德克国际物流",
        "sdsy888": "首达速运",
        "sdto": "速达通",
        "sedel": "守务国际货运",
        "seino": "西濃運輸",
        "sekologistics": "速客国际",
        "sendex": "Sendex",
        "sending": "Sending",
        "sendinglog": "森鼎国际物流",
        "sendle": "Sendle",
        "serbia": "塞尔维亚(PE Post of Serbia)",
        "seur": "International Seur",
        "seychellespost": "塞舌尔邮政(Seychelles Post)",
        "sfau": "澳丰速递",
        "sfc": "SFC",
        "sfcservice": "SFC Service",
        "sfift": "十方通物流",
        "sfydexpress": "速递管家",
        "sgtwl": "深港台物流",
        "sh9156": "升鸿国际物流",
        "shadowfax": "Shadowfax",
        "shallexp": "穗航物流",
        "shanda56": "衫达快运",
        "shangcheng": "尚橙物流",
        "shangda": "上大物流",
        "shangfang56": "尚方国际",
        "shanghaiwujiangmmb": "上海无疆for买卖宝",
        "shangqiao56": "商桥物流",
        "shangtuguoji": "尚途国际货运",
        "shanhuodidi": "闪货极速达",
        "shanxijianhua": "山西建华",
        "shaoke": "捎客物流",
        "shbwch": "杰响物流",
        "shd56": "商海德物流",
        "shenganwuliu": "圣安物流",
        "shengtongscm": "盛通快递",
        "shenjun": "神骏物流",
        "shenma": "神马快递",
        "shenzhoulenglian": "神州冷链",
        "shiligyl": "实利配送",
        "shiningexpress": "阳光快递",
        "shipa": "Shipa",
        "shipblu": "ShipBlu",
        "shipbyace": "王牌快递",
        "shipeag": "深圳老鹰跨境出口",
        "shipentegra": "ShipEntegra",
        "shipgreyhound": "Greyhound",
        "shippit": "shippit",
        "shipsoho": "苏豪快递",
        "shipwizmo": "Wizmo",
        "shiyunkuaidi": "世运快递",
        "shlexp": "SHL畅灵国际物流",
        "shlindao": "林道国际快递",
        "shopeexpress": "Shopee Express",
        "showl": "森鸿物流",
        "shpostwish": "wish邮",
        "shreeanjanicourier": "shreeanjanicourier",
        "shreemahabaliexpress": "Shree Mahabali Express",
        "shreemaruti": "Shree Maruti Courier",
        "shuanghe": "双鹤物流",
        "shunbang": "顺邦国际物流",
        "shunfengnl": "顺丰-荷兰",
        "shunjieda": "顺捷达",
        "shunjiefengda": "顺捷丰达",
        "shunyanwl": "顺衍物流",
        "shwise": "万色速递",
        "shxwl": "速汇星物流",
        "sicepat": "SiCepat Ekspres",
        "sihiexpress": "四海捷运",
        "sinoairinex": "中外运空运",
        "sinoex": "中外运速递-中文",
        "siodemka": "Siodemka",
        "sixroad": "易普递",
        "sjkd": "思捷快递",
        "sjtsz": "盛吉泰快递",
        "skr56": "斯格国际",
        "skuare": "世宽国际",
        "skyexpresseg": "Sky Express",
        "skynet": "skynet",
        "skynetmalaysia": "SkyNet Malaysia",
        "skynetworldwide": "skynetworldwide",
        "skypost": "荷兰Sky Post",
        "skypostal": "Asendia HK (LATAM)",
        "slovak": "斯洛伐克(Slovenská Posta)",
        "slovenia": "斯洛文尼亚(Slovenia Post)",
        "slpost": "斯里兰卡(Sri Lanka Post)",
        "smartcat": "黑猫跨境物流",
        "smartr": "Smartr Logistics",
        "smooth": "SMOOTH",
        "smsaexpress": "SMSA Express",
        "smwfloor": "湘粤华通",
        "sofast56": "嗖一下同城快递",
        "sogetras": "SGT Corriere Espresso",
        "solidlogistics": "上海昌迈供应链",
        "solomon": "所罗门群岛",
        "sonapost": "布基纳法索",
        "sooeasy": "水趣到家",
        "southafrican": "南非(South African Post Office)",
        "southamericapost": "南美邮联",
        "specialisedfreight": "Specialised Freight",
        "speeda": "行必达",
        "speedaf": "Speedaf",
        "speedafcncn": "速达非",
        "speedeedelivery": "Spee-Dee Delivery",
        "speedegypt": "Speed Shipping Company",
        "speedex": "SpeedEx",
        "speedoex": "申必达",
        "speedpost": "新加坡EMS、大包(Singapore Speedpost)",
        "speedx": "SpeedX",
        "speedy": "SPEEDY",
        "splexpress": "海港极速",
        "spoton": "Spoton",
        "spring": "Spring",
        "spring56": "春风物流",
        "sprint": "Sprint",
        "sprintpack": "SprintPack",
        "spsr": "中俄快递SPSR",
        "spssro": "Slovak Parcel Service",
        "spxph": "Shopee Xpress(PH)",
        "spxvn": "SPX VN",
        "srekorea": "SRE Korea",
        "ssd": "速速达",
        "staky": "首通快运",
        "stallionexpress": "Stallionexpress",
        "starex": "星速递",
        "starglobal": "航星国际物流",
        "starlinksme": "Starlinks",
        "startrack": "Star Track 快递",
        "starwish": "星希望供应链",
        "staryvr": "星运快递",
        "stepforwardfs": "STEPFORWARD",
        "stlucia": "圣卢西亚",
        "stmjwl": "深通茂江物流",
        "stoexpress": "美国申通",
        "straightship": "StraightShip",
        "subaoex": "速豹",
        "sucheng": "速呈宅配",
        "suchi8": "广东速驰",
        "sucmj": "特急便物流",
        "sudapost": "苏丹(Sudapost)",
        "suer": "速尔快递",
        "sufengkuaidi": "速风快递",
        "suijiawuliu": "穗佳物流",
        "sujievip": "郑州速捷",
        "sumxpress": "速玛物流",
        "suneng": "速能物流",
        "sunspeedy": "新速航",
        "superoz": "速配欧翼",
        "superton": "速宝通",
        "supinexpress": "速品快递",
        "surpost": "苏里南",
        "sutonghongda": "速通鸿达",
        "sutongst": "速通国际快运",
        "suyoukd": "速优国际快递",
        "svgpost": "圣文森特和格林纳丁斯",
        "swaziland": "斯威士兰",
        "swiship": "Amazon FBA Swiship",
        "swishipau": "Swiship AU",
        "swishipca": "Swiship CA",
        "swishipde": "Swiship DE",
        "swishipes": "Swiship ES",
        "swishipfr": "Swiship FR",
        "swishipit": "Swiship IT",
        "swishipjp": "Swiship JP",
        "swishipus": "swiship us",
        "swisspost": "瑞士(Swiss Post)",
        "swisspostcn": "瑞士邮政",
        "sxexpress": "三象速递",
        "sxhongmajia": "红马甲物流",
        "szac56": "澳辰国际",
        "szdpex": "深圳DPEX",
        "szendex": "Szendex",
        "szjdy": "金斗云物流",
        "szlinkexpress": "链客供应链",
        "szpago": "派格物流",
        "szsjtwl": "世纪通物流",
        "szty56": "通邮国际物流",
        "szxpwl": "兴鹏物流",
        "szyouzheng": "深圳邮政",
        "szzss": "中时顺物流",
        "taimek": "天美快递",
        "takesend": "泰嘉物流",
        "talabat": "Talabat",
        "tanzania": "坦桑尼亚(Tanzania Posts)",
        "taoplus": "淘布斯国际物流",
        "taote": "淘特物流快递",
        "taqbinhk": "香港宅急便",
        "taqbinmy": "TAQBIN 马来西亚",
        "tarrive": "通达物流",
        "tascourier": "TAScourier",
        "tawssil": "Tawssil",
        "taxydromiki": "Geniki Taxydromiki",
        "tcixps": "TCI XPS",
        "tcxbthai": "GPI",
        "tdzh": "天地纵横物流",
        "teamglobalexp": "Team Global Express (Toll IPEC)",
        "teapost": "亚欧快运TEA",
        "tengdawl": "腾达物流",
        "tfmxpress": "TFM Xpress",
        "tfs906": "天府盛",
        "thabitlogistics": "Thabit Logistics",
        "thailand": "泰国邮政(Thailand Thai Post)",
        "thebluebhellcouriers": "The BlueBhell Couriers",
        "thecourierguy": "The Courier Guy",
        "tianchenwuliu": "天辰物流",
        "tianma": "天马迅达",
        "tianxiang": "天翔快递",
        "tianyancha": "尚明物流",
        "tianyun": "天运国际",
        "tianzong": "天纵物流",
        "tiki": "TiKi",
        "tinghaowl": "挺好国际",
        "tipsa": "TIPSA",
        "tirupati": "Shree Tirupati",
        "tjlyz56": "老扬州物流",
        "tkkit": "Tk Kit",
        "tlky": "天联快运",
        "tmg": "株式会社T.M.G",
        "tmmexpress": "TMM",
        "tntau": "TNT Australia",
        "tntclick": "TNT Click",
        "tntfr": "TNT 法国",
        "tntitaly": "TNT Italy",
        "tntpostcn": "TNT Post",
        "tntuk": "TNT UK",
        "tobkk": "泰熊物流",
        "togo": "多哥",
        "tollpriority": "Toll Priority(Toll Online)",
        "tongapost": "汤加邮政(Tonga Post)",
        "tongdaxing": "通达兴物流",
        "tonghetianxia": "通和天下",
        "tongshengwj": "通胜物流",
        "tongshunda": "通顺达物流",
        "topshey": "顶世国际物流",
        "topspeedex": "中运全速",
        "toptrans": "Toptrans",
        "torbon": "Torbon",
        "tpcindia": "The Professional Couriers",
        "tpdex": "德启跨境供应链",
        "tql": "TQL",
        "trackoncourier": "Trackon Courier",
        "trackparcel": "track-parcel",
        "trackyourparcel": "Trackyourparcel",
        "trakpak": "TRAKPAK",
        "transkargologistics": "Trans Kargo",
        "transporter": "Transporter Egypt",
        "trendingtimes": "Trending Times",
        "trunkrs": "Trunkrs",
        "tstexp": "TST速运通",
        "ttsucha": "天天速查",
        "tunisia": "突尼斯EMS(Rapid-Poste)",
        "tunisiapost": "突尼斯邮政(Tunisia Post)",
        "turbo": "Turbo",
        "turtle": "海龟国际快递",
        "tuvalupost": "图瓦卢邮政(Tuvalu Post)",
        "tyjdwly": "天扬钧达",
        "tzgjw": "天正国际",
        "ubismartparcel": "UBI Logistics",
        "ubuylogi": "优拜物流",
        "ubx": "UBX",
        "ucs": "合众速递(UCS)",
        "udel": "UDEL",
        "uds56": "UDS",
        "ueq": "UEQ快递",
        "uex": "UEX国际物流",
        "uexiex": "欧洲UEX",
        "ufelix": "Ufelix",
        "uganda": "乌干达(Posta Uganda)",
        "ugoexpress": "邮鸽速运",
        "uhi": "优海国际速递",
        "ukmail": "UK Mail",
        "ukraine": "乌克兰小包、大包(UkrPoshta)",
        "ukrpostcn": "乌克兰邮政包裹",
        "uluckex": "优联吉运",
        "uniexpress": "Uni Express",
        "unioncourier": "Union Courier SAE",
        "uniteddelivery": "United Delivery Service",
        "unitedexpress": "United express courier service",
        "unline": "Un-line",
        "uparcel": "UParcel",
        "upsfreight": "UPS Freight",
        "upsmailinno": "UPS Mail Innovations",
        "upu": "UPU",
        "urbanfox": "UrBanFox",
        "urvaam": "Urvaam",
        "usa7ex": "美七国际快递",
        "usasueexpress": "速翼快递",
        "uscbexpress": "易境达国际物流",
        "uskyexpress": "全酋通Usky",
        "uspeedex": "优时派",
        "utaoscm": "UTAO优到",
        "utec": "UTEC瞬移达",
        "uvan56": "UVAN宇环通快递",
        "uzbekistan": "乌兹别克斯坦(Post of Uzbekistan)",
        "uzbekistanems": "EMS 乌兹别克斯坦",
        "valueway": "美通",
        "vanjexpress": "万加国际",
        "vanuatu": "瓦努阿图(Vanuatu Post)",
        "vctrans": "越中国际物流",
        "venipak": "Venipak",
        "vietnam": "越南小包(Vietnam Posts)",
        "viettelpost": "Viettel Post",
        "viewider": "Viewider",
        "vipexpress": "鹰运国际速递",
        "vnpost": "越南EMS(VNPost Express)",
        "voo": "Voo",
        "vovalogistics": "VOVA  Logistics",
        "vps": "维普恩物流",
        "wadily": "Wadily",
        "wahana": "Wahana",
        "walkerstransport": "Walkers Insight",
        "wanbexpress": "万邦速达",
        "wandougongzhu": "豌豆物流",
        "wanjiatong": "万家通急送",
        "wanjiwuliu": "万吉物流",
        "wanlijinxiu": "万里锦绣",
        "wanliwuliu": "万里物流",
        "wanyuyuntong": "万宇运通",
        "wassalnow": "WassalNow",
        "watt": "WATT",
        "wcxex": "WCXEX",
        "wdm": "万达美",
        "weareprocarrier": "Pro Carrier",
        "weaship": "Weaship",
        "wedel": "Wedel",
        "wedepot": "wedepot物流",
        "wedologistics": "WeDo Logistics",
        "welogistics": "世航通运",
        "wenjiesudi": "文捷航空",
        "weworldexpress": "We World Express",
        "wexpress": "威速递",
        "wexsu": "位像素",
        "whatsship": "Whats Ship",
        "whistl": "Whistl",
        "wingsing": "荣昇",
        "winit": "万邑通",
        "winlinklogistics": "合联国际物流",
        "wiseloads": "Wiseloads快递",
        "wishpost": "Wish邮政",
        "wlfast": "凡仕特物流",
        "wlwex": "星空国际",
        "wmgdelivery": "WMG Delivery",
        "wmycc": "万盟云仓",
        "wndirect": "wndirect快递",
        "wondersyd": "中邮速递",
        "wooolink": "上海领链物流",
        "worldex": "世通物流",
        "worldshipgd": "WSGD物流",
        "worldwidelogistics": "环世物流",
        "wotu": "渥途国际速运",
        "wowexpress": "wowexpress",
        "wpost56": "渭鹏速递",
        "wtdchina": "威时沛运货运",
        "wtdex": "WTD海外通",
        "wto56kj": "臣邦同城",
        "wuliuky": "五六快运",
        "wuyuansudi": "伍圆速递",
        "wwwexpress": "Wexpress",
        "wxgbwl": "广博物流",
        "wxjzwl": "九洲物流",
        "wxolys": "欧利",
        "wxyuanhui": "远辉物流",
        "wyngsmy": "WYNGS",
        "xdelogistics": "XDE Logistics",
        "xdexpress": "迅达速递",
        "xdpuk": "XDP Express",
        "xendph": "Xend Express",
        "xflt56": "蓝天物流",
        "xhf56": "鑫宏福物流",
        "xhongda56": "新宏达物流",
        "xianghua56": "响华速运",
        "xianglongyuntong": "祥龙运通物流",
        "xiangteng": "翔腾物流",
        "xilaikd": "西安喜来快递",
        "xindaexp": "鑫达快递",
        "xinganda": "兴安达物流",
        "xingsuexp": "星速国际",
        "xingyuankuaidi": "新元快递",
        "xingyunyi": "行运易",
        "xinmengcheng": "鑫梦成",
        "xinning": "新宁物流",
        "xinyan": "新颜物流",
        "xinyu": "鑫宇快运",
        "xinyuda": "鑫宇达",
        "xiongda": "雄达国际物流",
        "xiongjiu168": "雄九供应链",
        "xipost": "西邮寄",
        "xiyoug": "西游寄",
        "xlair": "快弟来了",
        "xmlxswl": "隆新顺物流",
        "xpertdelivery": "Xpert Delivery",
        "xpoweb": "Xpoweb",
        "xpressbees": "XpressBees",
        "xqkjwl": "星前物流",
        "xru": "XRU俄速递",
        "xsb56": "鑫圣邦物流",
        "xsexp": "新树物流",
        "xsrd": "鑫世锐达",
        "xtl": "讯田国际",
        "xunsuexpress": "迅速快递",
        "xunxuan": "迅选物流",
        "xyb2b": "行云物流",
        "xynyc": "新元国际",
        "xyslogistics": "XYS Logistics",
        "yafengsudi": "亚风速递",
        "yakit": "Yakit快递",
        "yanjingj": "延锦国际",
        "yaofeikuaidi": "耀飞同城快递",
        "yatai": "亚泰货运",
        "yatfai": "一辉物流",
        "ybdexpress": "邮必达",
        "ycgglobal": "YCG物流",
        "ycgky": "远成快运",
        "ydex": "一代国际",
        "ydexp": "羿德国际",
        "ydglobe": "云达通",
        "ydhex": "YDH",
        "ydl56": "亿德隆物流",
        "yemen": "也门(Yemen Post)",
        "yhtlogistics": "宇航通物流",
        "yibangwuliu": "一邦速递",
        "yidatong": "易达通",
        "yidazhuanyun": "EMAYYA",
        "yidihui": "驿递汇速递",
        "yidingmu": "一丁目",
        "yiex": "宜送物流",
        "yihangmall": "易航物流",
        "yijiangky": "驿将快运",
        "yikonn": "yikonn",
        "yilingsuyun": "亿领速运",
        "yilongex": "亿隆速运",
        "yilufawl": "一路发物流",
        "yingchao": "英超物流",
        "yingnuo": "英诺供应链",
        "yinhui56": "银辉物流",
        "yinjiesudi": "银捷速递",
        "yiouzhou": "易欧洲国际物流",
        "yiqisong": "一起送",
        "yishunhang": "亿顺航",
        "yisong": "宜送",
        "yitongda": "易通达",
        "yixiang": "易翔国际物流",
        "yizhengdasuyun": "一正达速运",
        "yjhgo": "武汉优进汇",
        "yjs": "益加盛快递",
        "ykouan": "洋口岸",
        "ylexp": "颐龙速递",
        "ylkswl": "亚历克斯供应链",
        "ylscm": "J&T云路供应链物流",
        "ynztsy": "黑猫同城送",
        "yodel": "YODEL",
        "yoseus": "优胜国际速递",
        "youban": "邮邦国际",
        "youjia": "友家速递",
        "youlai": "邮来速递",
        "yourscm": "雅澳物流",
        "yousutongda": "优速通达",
        "youyibang": "邮驿帮高铁速运",
        "youyou": "优优速递",
        "ysdpost": "优时达供应链",
        "ysexpress": "鼹鼠快送",
        "ystsd": "永世通物流",
        "ytchengnuoda": "承诺达",
        "ytky168": "运通快运",
        "yuanchengwuliu": "远成物流",
        "yuanhhk": "远航国际快运",
        "yuansuhy": "鸢速货运",
        "yue777": "玥玛速运",
        "yuefengwuliu": "越丰物流",
        "yufeng": "御风速运",
        "yugong56": "愚公物流",
        "yujiawl": "宇佳物流",
        "yujtong": "宇捷通",
        "yulin": "玉林物流",
        "yundaasia": "yundaasia",
        "yundaexus": "美国云达",
        "yunguo56": "蕴国物流",
        "yunjuwuliu": "云聚物流",
        "yurticikargo": "Yurtici Kargo",
        "yusen": "Yusen Logistics",
        "yutengguoji": "彧腾国际",
        "yuzhi56": "宇智物流",
        "ywbzexpress": "百洲货运",
        "yxilogistics": "悦希国际物流",
        "yyexp": "西安运逸快递",
        "yyexpress": "一沅国际物流",
        "yyqc56": "一运全成物流",
        "yzex": "顺联城",
        "yzk56": "源之康物流",
        "yztex": "一站通速运",
        "z1express": "宙一物流",
        "zajilship": "Zajil快递",
        "zampost": "赞比亚",
        "zbhy56": "浩运物流",
        "zeleris": "Zeleris",
        "zesexpress": "俄顺物流",
        "zf365": "珠峰速运",
        "zfex56": "志方物流",
        "zgtux": "途兴供应链",
        "zhanhon": "展宏物流",
        "zhaojin": "招金精炼",
        "zhdwl": "众辉达物流",
        "zhengqian": "正乾物流",
        "zhengyikuaidi": "鑫正一快递",
        "zhiguil": "智谷特货",
        "zhilianda": "智联达",
        "zhitengwuliu": "志腾物流",
        "zhonganhuoyun": "中安物流",
        "zhonghongwl": "中宏物流",
        "zhonghuan": "中环快递",
        "zhonghuanus": "中环转运",
        "zhongjiwuliu": "中技物流",
        "zhongkuai": "中快货运",
        "zhonglian": "众链供应链",
        "zhongtianwanyun": "中天万运",
        "zhongxinda": "忠信达",
        "zhongyouex": "众邮快递",
        "zhpex": "众派速递",
        "zhudiankuaiyun": "逐电快运",
        "zhuoqingwl": "卓庆物流",
        "zhuoshikuaiyun": "卓实快运",
        "zimlogistics": "以星物流",
        "zimpost": "津巴布韦邮政(Zimbabwe Post)",
        "zippyexpress": "Zippex",
        "zisone": "正石供应链",
        "zjcy56": "创运物流",
        "zjd123": "智杰达供应链",
        "zjgj56": "振捷国际货运",
        "zlwww": "众鹿物流",
        "zmcexpress": "ZMC EXPRESS",
        "zmetaport": "集合派",
        "zsda56": "转瞬达集运",
        "zsgjky": "飞速国际",
        "zsky123": "准实快运",
        "zsmhwl": "明辉物流",
        "zteexpress": "ZTE中兴物流",
        "ztjieda": "泰捷达国际物流",
        "ztong": "智通物流",
        "ztsdu": "中途国际速递",
        "zufall": "Zufall Germany",
        "zyouexpress": "众优",
        "zyzoom": "增速跨境"
    },
    expressState: {
        "1": "揽收",
        "101":"已下单",
        "102": "待揽收",
        "103": "已揽收",
        "0": "在途中",
        "1001": "到达目的地城市",
        "1002": "在途中",
        "1003": "在途中",
        "5": "正在派件",
        "501": "已到站或投柜",
        "3": "已签收",
        "301": "已本人签收",
        "302": "已签收",
        "303": "已代签收",
        "304": "已取出",
        "6": "退回",
        "4":"退签",
        "401": "已销单",
        "14": "拒签",
        "7": "转投",
        "2": "疑难",
        "201": "超时未签收",
        "202": "超时未更新",
        "203": "拒收",
        "204": "派件异常",
        "205": "柜或驿站超时未取",
        "206": "无法联系收件人",
        "207": "超区",
        "208": "在网点滞留",
        "209": "快件破损",
        "210": "销单",
        "8": "清关",
        "10": "待清关",
        "11": "清关中",
        "12": "已清关",
        "13": "清关异常"
    }
}